site_name: UniGrade
theme: 
    name: material
    language: 'pt'

repo_name: 'Unigrade'
repo_url: 'https://github.com/ads-unigrade-2019-1'

edit_uri: ''

nav:
    - Início: index.md
    - Definições do projeto:
        - Tema: definicoes_projeto/tema.md
        - Metodologia: definicoes_projeto/metodologia.md
        - Arquitetura: definicoes_projeto/arquitetura.md
    - Dinâmica e Seminário I:
        - 5w2h: dinamica01/5w2h.md
        - Rich Picture: dinamica01/richpicture.md
        - Argumentação: dinamica01/argumentacao.md
        - Diagrama Causa-Efeito: dinamica01/causaefeito.md
        - Mapa Mental: dinamica01/mapamental.md
        - Modelo de Custo Produtivo: dinamica01/cocomo.md 
    - Iniciativas Extras:
        - Relatórios das Reuniões:
            - Relatório I: iniciativas_extras/relatorios/relatorio1.md
            - Relatório II: iniciativas_extras/relatorios/relatorio2.md
