site_name: UniGrade
theme: 
    name: material
    language: 'pt'

repo_name: 'Unigrade'
repo_url: 'https://github.com/ads-unigrade-2019-1'

edit_uri: ''

nav:
    - Início: index.md
    - Definições do projeto:
        - Tema: definicoes_projeto/tema.md
        - Plano de Arquitetura: definicoes_projeto/arquitetura.md
    - Dinâmica e Seminário I:
        - 5w2h: dinamica01/5w2h.md
        - Rich Picture: dinamica01/richpicture.md
        - Argumentação: dinamica01/argumentacao.md
        - Diagrama Causa-Efeito: dinamica01/causaefeito.md
        - Mapa Mental: dinamica01/mapamental.md
        - Modelo de Custo Produtivo: dinamica01/cocomo.md 
    - Dinâmica e Seminário II:
        - Metodologia: dinamica02/metodologia.md
        - Plano de Gestão e Configuração de Software: dinamica02/GCS.md
        - Diagrama de Gantt: dinamica02/DiagramaGantt.md
        - Paralelo com Outras Metodologias: dinamica02/ParaleloMetodologias.md
        - Desenho da Metodologia: dinamica02/BPMN.md
    - Dinâmica e Seminário III:
        - Modelo Estático - API e Banco: dinamica03/apiebanco.md
        - Modelo Estático - App: dinamica03/app.md
        - Modelo Estático - WebScraper: dinamica03/webscrapper.md
    - Dinâmica e Seminário IV:
        - Modelo Dinâmico - API e Banco: dinamica04/apiebanco.md
        - Modelo Dinâmico - App: dinamica04/app.md
        - Modelo Dinâmico - WebScraper: dinamica04/webscrapper.md
    - Dinâmica e Seminário V:
        - GRASPs E GoFs - API: dinamica05A/api.md
        - GRASPs E GoFs - App: dinamica05A/app.md
        - GRASPs E GoFs - WebScraper: dinamica05A/webscraper.md
        - Padrões Emergentes - API: dinamica05B/api.md
        - Padrões Emergentes - App: dinamica05B/app.md
        - Padrões Emergentes - WebScraper: dinamica05B/webscraper.md
    - Dinâmica e Seminário VI:
        - Documento de Arquitetura: dinamica06/DAS.md
        - Architecture description language: dinamica06/ADL.md 
    - Iniciativas Extras:
        - Relatórios das Reuniões:
            - Relatório I: iniciativas_extras/relatorios/relatorio1.md
            - Relatório II: iniciativas_extras/relatorios/relatorio2.md
            - Relatório III: iniciativas_extras/relatorios/relatorio3.md
            - Relatório IV: iniciativas_extras/relatorios/relatorio4.md
            - Relatório V: iniciativas_extras/relatorios/relatorio5.md
            - Relatório VI: iniciativas_extras/relatorios/relatorio6.md
            - Relatório VII: iniciativas_extras/relatorios/relatorio7.md
            - Relatório VIII: iniciativas_extras/relatorios/relatorio8.md
            - Relatório IV: iniciativas_extras/relatorios/relatorio9.md
            - Relatório XI: iniciativas_extras/relatorios/relatorio11.md
        - NFR: iniciativas_extras/nfr.md
        - I*: iniciativas_extras/istar.md
        - SADT: iniciativas_extras/sadt.md
        - Documento de Visão: iniciativas_extras/sadt.md